# Generated by Django 5.0.3 on 2024-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('systemclaimno', models.CharField(max_length=50)),
                ('membernumber', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected', models.CharField(max_length=5)),
                ('reason', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('hsp', models.CharField(max_length=100)),
                ('ailment', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('batchno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'claim',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('relationship', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobilephone', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=100)),
                ('plans', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('membernumber', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('dateprinted', models.DateField()),
                ('exiteddate', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'main',
            },
        ),
    ]
